// Password 'lCxzTxao2ACCqX8q'
###
GET http://localhost:3000/products

### Create a product
POST http://localhost:3000/products
Content-Type: application/json

{
    "name" : "Parachichi la Mbeya", 
    "price" : 550
}
### GET product by its id
GET http://localhost:3000/products/642167d70092e4ebb0057a21

### UPDATE a product by its id
PATCH http://localhost:3000/products/642167d70092e4ebb0037a21
Content-Type: application/json

{
    "name": "Embe sindano ya Morogoro",
    "price" : 210
}

### DELETE product by id
DELETE http://localhost:3000/products/64252d6d133cc77ef620f648


### GET a page rather than products or specific product page
GET http://localhost:3000/

### Test request - GET
GET http://localhost:3000/test/5454/parachichi

### Test request - POST {application/json}
POST http://localhost:3000/test
Content-Type: application/json

{
    "name" : "Parachichi",
    "price" : 500
}

### Form URL-encoded
POST http://localhost:3000/test
Content-Type: application/x-www-form-urlencoded

name=parachichi&price=500